# Generated by Django 4.2.1 on 2023-06-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spa_web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("thumbnail", models.ImageField(upload_to="storage/image-projects")),
                ("deskripsi", models.TextField()),
            ],
            options={
                "db_table": "projects",
            },
        ),
    ]
